### PR TITLE
Adds basic support for the FTX websockets API

### PR DESCRIPTION
**Pull request by bvdaakster**
This PR adds a websocket client that handles the background ping messages and publishes other messages on a public queue.

Basic usage:
```python
async def main():
    ftx = FtxClient()
    # connect the websocket
    await ftx.websocket.connect()

    first_market = ftx.get_markets()[0]
    # subscribe to the trades channel of first available market
    await ftx.websocket.subscribe('trades', first_market['name'])

    while ftx.websocket.connected:
        # block and wait for next message from the queue
        msg = await ftx.websocket.recv()
        if 'channel' in msg and msg['channel'] == 'trades':
            if 'data' in msg:
                # print trade
                print(msg['market'], msg['data'][0]['side'], msg['data'][0]['size'])```

### CODE REVIEW

**Comment by CharlesFr** [comment]
@bvdaakster How come you closed this?

**Comment by bvdaakster** [comment]
@CharlesFr I realized I wanted to spend a bit more time on it... will create a new PR when ready

**Comment by CharlesFr** [comment]
Understood, do you mind sharing a few words on the use case?

**Comment by bvdaakster** [comment]
> Understood, do you mind sharing a few words on the use case?

Sure, the websocket allows us the ability to listen for messages in real-time, for FTX in particular it can be used to stream trades and orderbook updates as well as some other information.
https://docs.ftx.com/#websocket-api

I was looking for a Python library that had this feature for FTX but couldn't really find one so that's why I made this PR here. I am using it to listen for trades as they happen and then storing them in a database.

The `FtxClient.websocket` property lazily instantiates a `FtxWebSocketClient` with the same credentials as the client. The websocket client can also be instantiated with different credentials by using its constructor directly. 
The `FtxWebSocketClient` makes sure the websocket connection stays open by sending the ping message (as described on the FTX docs) every 15 seconds. Other messages received are pushed onto a queue which can be consumed by `FtxWebSocketClient.recv()`

Does that answer your question?

**Comment by bvdaakster** [comment]
@CharlesFr I've updated the PR and updated the readme file as well, let me know what you think

**Comment by gibz104** [comment]
> @CharlesFr I've updated the PR and updated the readme file as well, let me know what you think

This looks great!  I'd love to see this PR merged and have this ws functionality added to the master branch.  This is the only big thing currently missing from this repo.  Thanks for contributing this :)

**Pull request merged**
